/* OPERADORES LOGICOS 
/ && > AND > E
console.log(true && true) // && SO ACEITA SE AS DUAS CONDIÇÕES FOREM VERDADEIRAS

/ || > OR > OU 
console.log(true || false) // O OPERADOR LOGICO || PODE RETORNA TRUE SE UMA DAS CONDIÇÕES FOREM VERDADEIRAS, AGORA SE AS DUAS FOREM FALSAS IRA RETORNAR FALSE

/ ! > NOT > NÃO 
console.log(!true) / AQUI O OPERADOR DE NEGAÇÀO IRAR TROCAR O VALOR BOOLEANO DA CONDIÇÀO, SE O RESULTADO FOR TRUE IRAR SE FALSE, FALSE IRA VIRAR TRUEE 




*/
