/* OPERADORES ARRITMETICOS
   + ADIÇÃO / CONCATENAÇÃO
   () PARENTESES 
   - SUBTRAÇÃO
   / DIVISÃO
   * MULTIPLICAÇÃO
   % RESTO DA DIVISÃO
   ** POTENCIAÇÃO / 2 ** 10: 2 ELEVADO A 10, MULTIPLICA O 2 POR ELE MESMO 10 VEZES

// ORDEM DE PRESCEDENCIA
    1◦ PARENTESES
    2◦ POTENCIAÇÃO
    3◦ MULTIPLICAÇÃO / DIVISÃO / RESTO DIVISÃO
    4◦ ADIÇÃO / SUBTRAÇÃO

// OPERADOR DE INCREMENTO E DECREMENTO
    -- INCREMENTO / O MESMO QUE ESCREVER 1 - 1
    ++ DECREMENTO / O MESMO QUE ESCREVER 1 + 1

OBS: AO UTILIZAR O OPERADOR DE INCREMENTO NO INICIO PODERA OCORRER UMA AÇÃO, AO UTILIZAR ELE NO FINAL IRAR OCORRER OUTRA AÇAO,
EX: 
    LET CONTADOR = 1
    PÓS-INCREMENTO: CONTADOR++; // ELE IRA MOSTRAR 1 E LOGO APOS SERA ADIONADO MAIS UM
    PRE-INCREMENTO: ++CONTADOR; // AGORA ELE IRAR PRIMEIRO ADICIONAR O VALOR E DEPOIS MOSTRA CONTADOR + 1 = 2

    DA MESMA MANEIRA IRA ACONTECER COM O OPERADOR DE --
*/

let passo = 1
let contador = 0
passo **= 10
console.log(passo)