//ESCOPO LÉXICO
// O QUE É UM ESCOPO LÉXICO? ESCOPO LÉXICO É O LUGAR ONDE A FUNÇÃO FOI CRIADA, E ISSO DEFINE QUAIS VARIAVEIS ELA PODE ACESSAR EM SEU PROPRIO BLOCO, E SE NÃO ACHAR NO PROPRIO BLOCO, ELA PROCURA NOS BLOCOS DE FORA ATE CHEGAR AO BLOCO GLOBAL E SE MESMO ASSIM NÃO ENCONTRAR NADA IRA EXIBIR O ERRO 'IS NOT DEFINED' 

const nome = "gabriel"

function falaNome() {
    console.log(nome) // ELA IRAR PROCURAR PRIMEIRO A VARIAVEL NOME EM SEU ESCOPO( BLOCO ), SE NÃO ACHAR IRAR PULAR PARA O BLOCO ANTERIOR E ASSIM ATE CHEGAR NO ESCOPO GLOBAL E SE NO ESCOPO GLOBAL TAMBEM NÃO ENCONTRAR IRAR APRESENTAR O ERRO 'IS NOT DEFINED',
}

falaNome() // "gabriel"
