// let a = 'A'; // b
// let b = 'B'; // c 
// let c = 'C'; // a

// const letras = [b,c,a];
// [a,b,c] = letras;

// console.log(a,b,c)



/* ATRIBUINDO VALORES A VARIAVEIS VIA DESESTRUTURAÇÃO DE ARRAYS

const numeros = [10, 20, 30, 40, 50, 60, 70, 80, 90]
const [novonumero] = numeros   // AQUI EU ESTOU CRIANDO AS VARIAVEIS NOVONUMERO E ATRIBUINDO O INDICE ZERO( VALOR = 10 ) A ELA
console.log(novonumero)


// REST OPERATOR E SPREAD OPERATOR

const numeros = [10, 20, 30, 40, 50, 60, 70, 80, 90]
const [novonumero, ...resto] = numeros   // AQUI A VARIAVEL (...RESTO) ESTA RECEBENDO TODOS OS OUTROS INDICE QUE ESTIVEREM DENTRO DO ARRAY

...rest = REST OPERATOR, USADO QUANDO EU PRECISO PEGAR O RESTO DE ALGUMA COISA E MOSTRA-LO.
...spread = SPREAD OPERATOR, USADO QUANDO EU QUERO ESPALHAR ALGUMA COISA.

console.log(novonumero, resto) //   10 [  20, 30, 40, 50,  60, 70, 80, 90]


// PEGANDO VALORES ESPECIFICOS DO ARRAY

const numeros = [10, 20, 30, 40, 50, 60, 70, 80, 90]
const [UM,   ,TRES,   ,CINCO] = numeros   // QUANDO EU UTILIZO O ESPAÇO DENTRO DE UMA DESESTRUTURAÇÀO DESSA MANEIRA, SIGNIFICA QUE EU ESTOU PEGANDO VALORES ESPECIFICOS, NESSE CASO ( UM > 10, PULOU O VALOR 20, TRES > 30, PULOU O 40, CINCO > 50)

console.log(UM,TRES,CINCO) // 10 30 50


// DESESTRUTURAÇÀO E ATRIBUIÇÃO DE ARRAY DENTRO ARRAY  

1° MANEIRA 

const numeros = [ [11, 22, 33], [44, 55, 66], [77, 88, 99] ]
const [ZERO, ,DOIS] = numeros[0] // AQUI EU ESTOU PRIMEIRO SELECIONANDO O INDICE DA VARIAVEL NUMEROS[0], DEPOIS ESTOU CRIANDO DUAS VARIAVEIS(ZERO E DOIS) QUE TERAM DOIS VALORES DO INDICE NUMEROS[0].

console.log(SS) // 11  33, ELE PEGOU INDICE 0, E DENTRO DO INDICE 0 PEGOU OS INDICES 0 E 2 E JOGOU NAS VARIAVEIS ZERO E DOIS

2° MANEIRA

const [,[,,SEIS]] = numeros // AQUI EU ESTOU FAZENDO DIFERENTE, CADA VIRGULA PULA UM INDICE DO ARRAY, O COLCHETE[] É PARA ACESSAR O OUTRO OUTRO ARRAY QUE HA DENTRO DESSE ARRAY. 

console.log(SEIS) // 66, ELE PEGOU INDICE 1 E O INDICE 2  



*/


const numero = [ [ 11,22 ], [ [ 33,44 ], [ 55,66 ] ] ]
const [,[zero,um]] = numero[1] 

console.log(zero, um)
