// CLOSURE
// O QUE É CLOSURE?  É QUANDO UM ESCOPO EXTERNO É EXECUTADO, E RETORNA UM ESCOPO INTERNO, MAS ESSE ESCOPO INTERNO AINDA CONSEGUE ACESSAR INFORMAÇÕES DO ESCOPO ESCOPO I\XNTERNO, COMO VARIAVEIS OU PARAMETROS.
// CLOSURE É QUANDO UMA FUNÇÃO INTERNA MANTÉM ACESSO AO ESCOPO DA FUNÇÃO EXTERNA, MESMO APÓS A EXTERNA JÁ TER SIDO EXECUTADA 

function retornaFuncao() { /// ESCOPO EXTERNO
    const nome = 'Gabriel'
    return function () { // ESCOPO INTERNO
        console.log(nome) 
    }
}

const funcao = retornaFuncao() // A PARTIR DESSE MOMENTO O ESCOPO EXTERNO TERMINOU A SUA EXECUÇÃO, MAS COMO A FUNÇÃP INTERNA AINDA PRECISA DE ALGO DA FUNÇÃO INTERNA O JS AINDA MANTEM VIVA ATRAVES DO CLOSURE.
funcao() // AQUI A FUNÇÃO INTERNA FOI CHAMADA, COMO O ESCOPO LEXICO NÃO ACHOU A VARIAVEL 'NOME' NO SEU BLOCO ELE PROCUROU NO CLOSURE DO ESCOPO EXTERNO E ENCONTROU.

