/* OPERADORES DE COMPARAÇÃO
> MAIOR QUE
console.log(10 > 5) // IRAR RETORNAR TRUE, POIS 10 É MAIOR QUE 5.;

>= MAIOR OU IGUAL
console.log(10 >= 5) // IRAR RETORNAR TRUE TBM, SO QUE AGORA TEMOS 2 OPÇÕES,MAIOR(>) OU IGUAL(=) A 5.;

< MENOR QUE 
console.log(5 < 10) // AQUI IRAR VERIFICAR SE 5 É MENOR DO QUE 10, NO CASO IRAR RETORNAR TRUE, 5 É MENOR QUE 10.;

<= MENOR OU IGUAL
console.log(5 <= 10) // AQUI JÁ ESTAMOS VERIFICANDO 2 OPÇÕES, SE 5 É MENOR QUE 10(TRUE) E SE 5 É IGUAL A 10.;

== IGUAL ( VERIFICA O VALOR)
console.log(10 == 5) // AQUI SÓ ACEITAMOS 1 OPÇÃO, 10 É IGUAL A 5? NÃO. ENTÃO NESSE CASO TEREMOS FALSE

=== IGUALDADE ESTRITA ( VERIFICA O VALOR E TBM O TIPO )x
console.log(10 === '10') // AQUI VISUALMENTE TEMOS 2 NUMEROS IGUAIS, MAS COM TIPOS DIFERENTES, 10(NUMBER) === '10'(STRING) IGUAL A FALSE

!= DIFERENTE ( VERIFICA O VALOR)
console.log(10 != '10') // AQUI IREMOS COMPARAR OS DOIS NUMEROS, 10 É DIFERENTE DE 10? VISUALMENTE NÃO. SÃO TIPOS DIFERENTES, MAS ELE NÃO VERIFICOU OS TIPOS, ENTÃO RETORNARA 'FALSE' 

!== DIFERENTE ESTRITO ( VERIFICA O VALOR E TIPO)
console.log(10 !== '10') // AQUI IREMOS COMPARAR OS DOIS NUMEROS NOVAMENTE, 10 É DIFERENTE DE '10'? SIM. POIS AQUI ELA JÁ ESTA COMPARANDO OS VALORES E OS TIPOS DELES (STRING) E (NUMBER), ENTÃO RETORNARA 'TRUE'.; 
*/